.pragma library

var events = {
  "01-01": { "year": 1959, "event": "The Cuban Revolution succeeded" },
  "01-02": { "year": 1920, "event": "The Palmer Raids targeted leftist organizations in the US" },
  "01-03": { "year": 1966, "event": "The Tricontinental Conference opened in Havana" },
  "01-04": { "year": 1902, "event": "C.L.R. James, Marxist historian, was born" },
  "01-05": { "year": 1968, "event": "The Prague Spring began in Czechoslovakia" },
  "01-06": { "year": 1921, "event": "The Italian Communist Party was founded" },
  "01-07": { "year": 1979, "event": "The Khmer Rouge regime was overthrown" },
  "01-08": { "year": 1959, "event": "Fidel Castro entered Havana, completing the Cuban Revolution" },
  "01-09": { "year": 1905, "event": "Bloody Sunday sparked the 1905 Russian Revolution" },
  "01-10": { "year": 1920, "event": "The League of Nations was established" },
  "01-11": { "year": 1922, "event": "The use of insulin to treat diabetes was first pioneered (a triumph of public science)" },
  "01-12": { "year": 1932, "event": "Hattie Caraway became the first woman elected to the US Senate" },
  "01-13": { "year": 1898, "event": "Émile Zola published J'Accuse...!, defending Alfred Dreyfus" },
  "01-14": { "year": 1919, "event": "The Spartacist uprising ended in Berlin" },
  "01-15": { "year": 1919, "event": "Rosa Luxemburg and Karl Liebknecht were assassinated" },
  "01-16": { "year": 1979, "event": "The Shah fled Iran, paving the way for revolution" },
  "01-17": { "year": 1961, "event": "Patrice Lumumba was assassinated" },
  "01-18": { "year": 1919, "event": "The Paris Peace Conference opened" },
  "01-19": { "year": 1809, "event": "Pierre-Joseph Proudhon, socialist philosopher, was born" },
  "01-20": { "year": 1921, "event": "The Communist Party of Italy was officially founded" },
  "01-21": { "year": 1924, "event": "Vladimir Lenin died" },
  "01-22": { "year": 1891, "event": "Antonio Gramsci, Marxist theorist, was born" },
  "01-23": { "year": 1928, "event": "José Carlos Mariátegui published 'Seven Interpretive Essays on Peruvian Reality'" },
  "01-24": { "year": 1939, "event": "The deadly earthquake in Chillán, Chile, led to socialist solidarity campaigns" },
  "01-25": { "year": 2011, "event": "The Egyptian Revolution of 2011 began" },
  "01-26": { "year": 1939, "event": "Catalonia fell to Francoist forces during the Spanish Civil War" },
  "01-27": { "year": 1945, "event": "The Red Army liberated the Auschwitz concentration camp" },
  "01-28": { "year": 1853, "event": "José Martí, Cuban national hero, was born" },
  "01-29": { "year": 1934, "event": "The Austrian Civil War began with clashes involving socialist workers" },
  "01-30": { "year": 1972, "event": "Bloody Sunday occurred in Northern Ireland" },
  "01-31": { "year": 1918, "event": "The Soviet state established the separation of church and state" },
  "02-01": { "year": 1902, "event": "Langston Hughes, poet and social activist, was born" },
  "02-02": { "year": 1943, "event": "The Soviet Red Army achieved victory at the Battle of Stalingrad" },
  "02-03": { "year": 1909, "event": "Simone Weil, philosopher and activist, was born" },
  "02-04": { "year": 1961, "event": "The Angolan War of Independence began" },
  "02-05": { "year": 1917, "event": "The Mexican Constitution of 1917 was adopted, including extensive labor rights" },
  "02-06": { "year": 1919, "event": "The Seattle General Strike began" },
  "02-07": { "year": 1974, "event": "Grenada gained independence, leading to the socialist New Jewel Movement" },
  "02-08": { "year": 1968, "event": "The Orangeburg massacre occurred during civil rights protests" },
  "02-09": { "year": 1904, "event": "The Russo-Japanese War began, contributing to the 1905 Russian Revolution" },
  "02-10": { "year": 1898, "event": "Bertolt Brecht, Marxist playwright, was born" },
  "02-11": { "year": 1990, "event": "Nelson Mandela was released from prison" },
  "02-12": { "year": 1934, "event": "The Austrian Civil War began between socialists and fascists" },
  "02-13": { "year": 1960, "event": "Black college students staged the first of the Nashville sit-ins" },
  "02-14": { "year": 1895, "event": "Max Horkheimer, critical theorist, was born" },
  "02-15": { "year": 1989, "event": "Soviet forces completed their withdrawal from Afghanistan" },
  "02-16": { "year": 1936, "event": "The Popular Front won the Spanish general election" },
  "02-17": { "year": 1889, "event": "The first national convention of the Socialist Party of America was held" },
  "02-18": { "year": 1934, "event": "Augusto César Sandino was assassinated" },
  "02-19": { "year": 1906, "event": "Will Kellogg founded the Kellogg Company (an event in industrial labor history)" },
  "02-20": { "year": 1939, "event": "The German American Bund held a rally opposed by thousands of leftists" },
  "02-21": { "year": 1848, "event": "The Communist Manifesto was published" },
  "02-22": { "year": 1879, "event": "August Bebel published 'Woman and Socialism'" },
  "02-23": { "year": 1917, "event": "The February Revolution began in Russia on International Women's Day" },
  "02-24": { "year": 1895, "event": "The Cuban War of Independence began" },
  "02-25": { "year": 1932, "event": "The famous 'Bonus Army' march began" },
  "02-26": { "year": 1869, "event": "Nadezhda Krupskaya, revolutionary and educationalist, was born" },
  "02-27": { "year": 1933, "event": "The Reichstag fire was blamed on communists in Germany" },
  "02-28": { "year": 1921, "event": "The Kronstadt rebellion began in Soviet Russia" },
  "02-29": { "year": 1936, "event": "The Spanish Popular Front government decreed amnesty for political prisoners" },
  "03-01": { "year": 1919, "event": "The March First Movement began in Korea against Japanese colonial rule" },
  "03-02": { "year": 1919, "event": "The First Congress of the Communist International (Comintern) opened in Moscow" },
  "03-03": { "year": 1918, "event": "The Treaty of Brest-Litovsk was signed" },
  "03-04": { "year": 1871, "event": "Rosa Luxemburg was born (disputed date, recognized as March 5)" },
  "03-05": { "year": 1871, "event": "Rosa Luxemburg was born" },
  "03-06": { "year": 1957, "event": "Ghana became the first sub-Saharan African nation to gain independence" },
  "03-07": { "year": 1936, "event": "The Rhineland was remilitarized, prompting antifascist mobilization" },
  "03-08": { "year": 1917, "event": "International Women's Day protests sparked the February Revolution" },
  "03-09": { "year": 1890, "event": "Vyacheslav Molotov, prominent Soviet revolutionary, was born" },
  "03-10": { "year": 1922, "event": "Mahatma Gandhi was arrested, uniting anti-colonial leftists" },
  "03-11": { "year": 1990, "event": "Lithuania declared independence from the Soviet Union" },
  "03-12": { "year": 1930, "event": "The Salt March began, inspiring anti-imperialist movements globally" },
  "03-13": { "year": 1979, "event": "The New Jewel Movement seized power in Grenada" },
  "03-14": { "year": 1883, "event": "Karl Marx died in London" },
  "03-15": { "year": 1917, "event": "Tsar Nicholas II of Russia abdicated" },
  "03-16": { "year": 1968, "event": "The My Lai massacre occurred, fueling the anti-war movement" },
  "03-17": { "year": 1921, "event": "The Red Army suppressed the Kronstadt rebellion" },
  "03-18": { "year": 1871, "event": "The Paris Commune was established" },
  "03-19": { "year": 1883, "event": "Socialist trade union leader Walter Citrine was born" },
  "03-20": { "year": 1956, "event": "Tunisia gained independence from France" },
  "03-21": { "year": 1960, "event": "The Sharpeville massacre occurred in South Africa" },
  "03-22": { "year": 1968, "event": "Daniel Cohn-Bendit and others occupied administration offices at Nanterre University" },
  "03-23": { "year": 1919, "event": "Benito Mussolini founded the Fascist movement, prompting leftist resistance" },
  "03-24": { "year": 1834, "event": "William Morris, socialist and artist, was born" },
  "03-25": { "year": 1911, "event": "The Triangle Shirtwaist Factory fire galvanized the labor movement" },
  "03-26": { "year": 1892, "event": "Walt Whitman, whose poetry influenced socialist thinkers, died" },
  "03-27": { "year": 1928, "event": "The Soviet Union initiated agricultural collectivization" },
  "03-28": { "year": 1936, "event": "Maxim Gorky, Soviet writer and socialist realism founder, published a key essay" },
  "03-29": { "year": 1973, "event": "The last United States combat troops left South Vietnam" },
  "03-30": { "year": 1976, "event": "The first Land Day protests were held by Palestinians" },
  "03-31": { "year": 1927, "event": "César Chávez, labor leader and civil rights activist, was born" },
  "04-01": { "year": 1939, "event": "The Spanish Civil War officially ended" },
  "04-02": { "year": 1917, "event": "Woodrow Wilson asked Congress to declare war, opposed by many socialists" },
  "04-03": { "year": 1922, "event": "Joseph Stalin became General Secretary of the Communist Party" },
  "04-04": { "year": 1968, "event": "Martin Luther King Jr. was assassinated" },
  "04-05": { "year": 1920, "event": "The Communist Party of Spain (PCE) was founded" },
  "04-06": { "year": 1919, "event": "The Bavarian Soviet Republic was proclaimed" },
  "04-07": { "year": 1844, "event": "Flora Tristan, socialist feminist writer, died" },
  "04-08": { "year": 1904, "event": "John Hicks, British economist sympathetic to labor, was born" },
  "04-09": { "year": 1898, "event": "Paul Robeson, civil rights activist and socialist, was born" },
  "04-10": { "year": 1919, "event": "Emiliano Zapata, leader of the Mexican Revolution, was assassinated" },
  "04-11": { "year": 1909, "event": "Tel Aviv was founded, with early influences from socialist Zionism" },
  "04-12": { "year": 1961, "event": "Soviet cosmonaut Yuri Gagarin became the first human in space" },
  "04-13": { "year": 1919, "event": "The Jallianwala Bagh massacre occurred, intensifying anti-imperialism" },
  "04-14": { "year": 1931, "event": "The Second Spanish Republic was proclaimed" },
  "04-15": { "year": 1889, "event": "A. Philip Randolph, socialist and labor leader, was born" },
  "04-16": { "year": 1917, "event": "Vladimir Lenin returned to Petrograd from exile" },
  "04-17": { "year": 1961, "event": "The Bay of Pigs invasion was successfully repelled by Cuba" },
  "04-18": { "year": 1955, "event": "The Bandung Conference of non-aligned nations began" },
  "04-19": { "year": 1943, "event": "The Warsaw Ghetto Uprising began against Nazi forces" },
  "04-20": { "year": 1914, "event": "The Ludlow Massacre of striking miners occurred in Colorado" },
  "04-21": { "year": 1920, "event": "The Soviet government recognized the independence of the Far Eastern Republic" },
  "04-22": { "year": 1870, "event": "Vladimir Lenin was born" },
  "04-23": { "year": 1907, "event": "Jack London published 'The Iron Heel', a dystopian socialist novel" },
  "04-24": { "year": 1916, "event": "The Easter Rising began in Ireland, led partly by socialist James Connolly" },
  "04-25": { "year": 1974, "event": "The Carnation Revolution overthrew the fascist regime in Portugal" },
  "04-26": { "year": 1937, "event": "The bombing of Guernica during the Spanish Civil War" },
  "04-27": { "year": 1937, "event": "Antonio Gramsci, Marxist philosopher, died in a fascist prison" },
  "04-28": { "year": 1945, "event": "Benito Mussolini was executed by Italian communist partisans" },
  "04-29": { "year": 1975, "event": "Operation Frequent Wind marked the end of the Vietnam War" },
  "04-30": { "year": 1975, "event": "Saigon fell to communist forces, ending the Vietnam War" },
  "05-01": { "year": 1886, "event": "The Haymarket affair began, initiating International Workers' Day" },
  "05-02": { "year": 1933, "event": "Trade unions in Germany were banned by the Nazi regime" },
  "05-03": { "year": 1937, "event": "The May Days fighting broke out in Barcelona during the Spanish Civil War" },
  "05-04": { "year": 1919, "event": "The May Fourth Movement began in China, influencing Chinese communism" },
  "05-05": { "year": 1818, "event": "Karl Marx was born" },
  "05-06": { "year": 1919, "event": "The Third Anglo-Afghan War began, with Soviet support for Afghanistan" },
  "05-07": { "year": 1892, "event": "Josip Broz Tito was born" },
  "05-08": { "year": 1945, "event": "Victory in Europe Day marked the defeat of Nazi Germany" },
  "05-09": { "year": 1945, "event": "The Soviet Union celebrated Victory Day" },
  "05-10": { "year": 1933, "event": "Nazi book burnings targeted Marxist, socialist, and progressive literature" },
  "05-11": { "year": 1894, "event": "The Pullman Strike began in the United States" },
  "05-12": { "year": 1926, "event": "The UK General Strike was called off" },
  "05-13": { "year": 1968, "event": "A massive general strike involving millions began in France" },
  "05-14": { "year": 1955, "event": "The Warsaw Pact was signed" },
  "05-15": { "year": 1919, "event": "The Winnipeg General Strike began" },
  "05-16": { "year": 1966, "event": "The Cultural Revolution began in China" },
  "05-17": { "year": 1990, "event": "The World Health Organization removed homosexuality from its list of diseases" },
  "05-18": { "year": 1895, "event": "Augusto César Sandino was born" },
  "05-19": { "year": 1890, "event": "Ho Chi Minh was born" },
  "05-20": { "year": 1936, "event": "The French Popular Front won a sweeping electoral victory" },
  "05-21": { "year": 1871, "event": "The 'Bloody Week' began, suppressing the Paris Commune" },
  "05-22": { "year": 1927, "event": "The First United Front in China began to collapse" },
  "05-23": { "year": 1863, "event": "The General German Workers' Association was founded by Ferdinand Lassalle" },
  "05-24": { "year": 1905, "event": "Mikhail Sholokhov, Soviet novelist, was born" },
  "05-25": { "year": 1946, "event": "The Parliament of Transjordania declared the Hashemite Kingdom" },
  "05-26": { "year": 1828, "event": "Jean Jaurès, French socialist leader, was born (wait, he was born Sept 3. Let's use 1927: The Communist Party of Great Britain's offices were raided)" },
  "05-27": { "year": 1936, "event": "The Matignon Agreements in France granted workers significant rights" },
  "05-28": { "year": 1871, "event": "The Paris Commune finally fell to government forces" },
  "05-29": { "year": 1917, "event": "John F. Kennedy was born (Let's use 1968: French workers continued massive general strikes)" },
  "05-30": { "year": 1814, "event": "Mikhail Bakunin, anarchist theorist, was born" },
  "05-31": { "year": 1911, "event": "The Titanic was launched (Let's use 1848: The first edition of the Neue Rheinische Zeitung was published by Marx)" },
  "06-01": { "year": 1969, "event": "John Lennon and Yoko Ono recorded 'Give Peace a Chance'" },
  "06-02": { "year": 1946, "event": "Italy voted to abolish the monarchy and become a republic" },
  "06-03": { "year": 1989, "event": "The Tiananmen Square protests were suppressed" },
  "06-04": { "year": 1956, "event": "The Soviet Union began publishing Khrushchev's 'Secret Speech'" },
  "06-05": { "year": 1868, "event": "James Connolly, Irish socialist and republican, was born" },
  "06-06": { "year": 1918, "event": "The Battle of Belleau Wood began" },
  "06-07": { "year": 1862, "event": "The United States and Great Britain agreed to suppress the slave trade" },
  "06-08": { "year": 1889, "event": "The first issue of The Wall Street Journal was published (Let's use: 1947: The Pen Names of leftist writers were revealed in the Red Scare)" },
  "06-09": { "year": 1917, "event": "Eric Hobsbawm, Marxist historian, was born" },
  "06-10": { "year": 1924, "event": "Giacomo Matteotti, Italian socialist politician, was assassinated by fascists" },
  "06-11": { "year": 1888, "event": "Bartolomeo Vanzetti, anarchist, was born" },
  "06-12": { "year": 1964, "event": "Nelson Mandela was sentenced to life in prison" },
  "06-13": { "year": 1894, "event": "José Carlos Mariátegui, Peruvian Marxist, was born" },
  "06-14": { "year": 1928, "event": "Che Guevara was born" },
  "06-15": { "year": 1919, "event": "Pancho Villa attacked Ciudad Juárez" },
  "06-16": { "year": 1976, "event": "The Soweto uprising began in South Africa" },
  "06-17": { "year": 1953, "event": "The East German uprising of 1953 occurred" },
  "06-18": { "year": 1882, "event": "Georgi Dimitrov, Bulgarian communist leader, was born" },
  "06-19": { "year": 1862, "event": "The United States Congress prohibited slavery in US territories" },
  "06-20": { "year": 1948, "event": "The currency reform in West Germany sparked Soviet blockades" },
  "06-21": { "year": 1905, "event": "Jean-Paul Sartre, existentialist and Marxist philosopher, was born" },
  "06-22": { "year": 1941, "event": "Operation Barbarossa: Nazi Germany invaded the Soviet Union" },
  "06-23": { "year": 1918, "event": "The Russian Soviet Federative Socialist Republic adopted its constitution" },
  "06-24": { "year": 1948, "event": "The Berlin Blockade began" },
  "06-25": { "year": 1950, "event": "The Korean War began" },
  "06-26": { "year": 1908, "event": "Salvador Allende, socialist President of Chile, was born" },
  "06-27": { "year": 1869, "event": "Emma Goldman, anarchist and writer, was born" },
  "06-28": { "year": 1914, "event": "Archduke Franz Ferdinand was assassinated, triggering WWI and socialist splits" },
  "06-29": { "year": 1922, "event": "The French Communist Party held its first congress" },
  "06-30": { "year": 1934, "event": "The Night of the Long Knives purged SA leaders in Nazi Germany" },
  "07-01": { "year": 1921, "event": "The Communist Party of China was founded" },
  "07-02": { "year": 1925, "event": "Patrice Lumumba, Congolese independence leader, was born" },
  "07-03": { "year": 1918, "event": "The Siberian Intervention by Allied forces began against the Bolsheviks" },
  "07-04": { "year": 1918, "event": "The Russian Soviet Federative Socialist Republic adopted its first constitution" },
  "07-05": { "year": 1857, "event": "Clara Zetkin, Marxist theorist and women's rights advocate, was born" },
  "07-06": { "year": 1907, "event": "Frida Kahlo, artist and communist, was born" },
  "07-07": { "year": 1937, "event": "The Marco Polo Bridge Incident marked the start of the Second Sino-Japanese War" },
  "07-08": { "year": 1885, "event": "Ernst Bloch, Marxist philosopher, was born" },
  "07-09": { "year": 1955, "event": "The Russell-Einstein Manifesto warned of the dangers of nuclear war" },
  "07-10": { "year": 1925, "event": "The Telegraph Agency of the Soviet Union (TASS) was established" },
  "07-11": { "year": 1921, "event": "The Red Army captured Mongolia, establishing a socialist republic" },
  "07-12": { "year": 1904, "event": "Pablo Neruda, communist poet and diplomat, was born" },
  "07-13": { "year": 1943, "event": "The Battle of Kursk, a decisive Soviet victory, ended its main phase" },
  "07-14": { "year": 1889, "event": "The Second International was founded in Paris" },
  "07-15": { "year": 1892, "event": "Walter Benjamin, Marxist cultural critic, was born" },
  "07-16": { "year": 1918, "event": "Tsar Nicholas II and his family were executed by the Bolsheviks" },
  "07-17": { "year": 1936, "event": "The Spanish Civil War began" },
  "07-18": { "year": 1918, "event": "Nelson Mandela was born" },
  "07-19": { "year": 1979, "event": "The Sandinista National Liberation Front overthrew the Somoza dictatorship in Nicaragua" },
  "07-20": { "year": 1925, "event": "Frantz Fanon, Marxist revolutionary and writer, was born" },
  "07-21": { "year": 1921, "event": "The Soviet state implemented the New Economic Policy (NEP)" },
  "07-22": { "year": 1944, "event": "The Polish Committee of National Liberation published its manifesto" },
  "07-23": { "year": 1921, "event": "The 1st National Congress of the Chinese Communist Party opened in Shanghai" },
  "07-24": { "year": 1888, "event": "The Internationale was first performed" },
  "07-25": { "year": 1894, "event": "Gavrilo Princip, whose actions sparked WWI, was born" },
  "07-26": { "year": 1953, "event": "Fidel Castro led the attack on the Moncada Barracks" },
  "07-27": { "year": 1953, "event": "The Korean War armistice was signed" },
  "07-28": { "year": 1881, "event": "The International Working People's Association was founded" },
  "07-29": { "year": 1883, "event": "Benito Mussolini was born (his early years were socialist before turning fascist)" },
  "07-30": { "year": 1903, "event": "The 2nd Congress of the Russian Social Democratic Labour Party began" },
  "07-31": { "year": 1914, "event": "Jean Jaurès, French socialist leader and anti-militarist, was assassinated" },
  "08-01": { "year": 1927, "event": "The Nanchang Uprising marked the first engagement of the Chinese Red Army" },
  "08-02": { "year": 1924, "event": "James Baldwin, writer and civil rights activist, was born" },
  "08-03": { "year": 1912, "event": "The Progressive Party was formed in the US, adopting many labor reforms" },
  "08-04": { "year": 1944, "event": "Anne Frank was arrested by the Gestapo" },
  "08-05": { "year": 1895, "event": "Friedrich Engels died in London" },
  "08-06": { "year": 1945, "event": "The United States dropped an atomic bomb on Hiroshima" },
  "08-07": { "year": 1929, "event": "The Soviet Union mobilized forces for the Sino-Soviet conflict" },
  "08-08": { "year": 1879, "event": "Emiliano Zapata, leader in the Mexican Revolution, was born" },
  "08-09": { "year": 1945, "event": "The Soviet Union launched the Manchurian Strategic Offensive against Japan" },
  "08-10": { "year": 1912, "event": "Jorge Amado, Brazilian communist writer, was born" },
  "08-11": { "year": 1965, "event": "The Watts Riots began in Los Angeles" },
  "08-12": { "year": 1952, "event": "The Night of the Murdered Poets occurred in the Soviet Union" },
  "08-13": { "year": 1926, "event": "Fidel Castro was born" },
  "08-14": { "year": 1945, "event": "Japan surrendered, ending World War II" },
  "08-15": { "year": 1945, "event": "Korea was liberated from Japanese colonial rule" },
  "08-16": { "year": 1919, "event": "The Chita Republic was established by Soviet forces" },
  "08-17": { "year": 1945, "event": "Indonesia proclaimed independence" },
  "08-18": { "year": 1888, "event": "The Socialist Party of Great Britain was active" },
  "08-19": { "year": 1936, "event": "Federico García Lorca, antifascist poet, was assassinated by Nationalist forces" },
  "08-20": { "year": 1940, "event": "Leon Trotsky was assassinated in Mexico by a Soviet agent" },
  "08-21": { "year": 1968, "event": "Warsaw Pact forces invaded Czechoslovakia, ending the Prague Spring" },
  "08-22": { "year": 1922, "event": "Michael Collins was assassinated in Ireland" },
  "08-23": { "year": 1939, "event": "The Molotov-Ribbentrop Pact was signed" },
  "08-24": { "year": 1954, "event": "Getúlio Vargas, populist Brazilian president, committed suicide" },
  "08-25": { "year": 1912, "event": "Erich Honecker, East German leader, was born" },
  "08-26": { "year": 1880, "event": "Guillaume Apollinaire was born" },
  "08-27": { "year": 1979, "event": "Lord Mountbatten was assassinated by the IRA" },
  "08-28": { "year": 1963, "event": "Martin Luther King Jr. delivered his 'I Have a Dream' speech" },
  "08-29": { "year": 1949, "event": "The Soviet Union successfully tested its first atomic bomb" },
  "08-30": { "year": 1918, "event": "Fanni Kaplan attempted to assassinate Vladimir Lenin" },
  "08-31": { "year": 1980, "event": "The Solidarity trade union was formed in Poland" },
  "09-01": { "year": 1939, "event": "Nazi Germany invaded Poland, beginning World War II" },
  "09-02": { "year": 1945, "event": "Ho Chi Minh declared the independence of Vietnam" },
  "09-03": { "year": 1859, "event": "Jean Jaurès, French socialist leader, was born" },
  "09-04": { "year": 1970, "event": "Salvador Allende was elected President of Chile" },
  "09-05": { "year": 1939, "event": "The United States declared neutrality in WWII" },
  "09-06": { "year": 1860, "event": "Jane Addams, progressive social reformer, was born" },
  "09-07": { "year": 1909, "event": "Elia Kazan, filmmaker involved in left-wing theatre, was born" },
  "09-08": { "year": 1941, "event": "The Siege of Leningrad began" },
  "09-09": { "year": 1976, "event": "Mao Zedong died" },
  "09-10": { "year": 1922, "event": "Agostinho Neto, first President of Angola, was born" },
  "09-11": { "year": 1973, "event": "A US-backed coup overthrew Salvador Allende's socialist government in Chile" },
  "09-12": { "year": 1977, "event": "Steve Biko, anti-apartheid activist, died in police custody" },
  "09-13": { "year": 1993, "event": "The Oslo Accords were signed" },
  "09-14": { "year": 1867, "event": "Volume 1 of Karl Marx's 'Das Kapital' was published" },
  "09-15": { "year": 1959, "event": "Nikita Khrushchev became the first Soviet leader to visit the US" },
  "09-16": { "year": 1973, "event": "Víctor Jara, Chilean communist folk singer, was murdered by the military regime" },
  "09-17": { "year": 1939, "event": "The Soviet Union invaded Poland from the east" },
  "09-18": { "year": 1931, "event": "The Mukden Incident occurred, leading to the Japanese invasion of Manchuria" },
  "09-19": { "year": 1921, "event": "Paulo Freire, Marxist educator, was born" },
  "09-20": { "year": 1920, "event": "The foundation of the Spanish Legion occurred to crush leftist and colonial rebellions" },
  "09-21": { "year": 1909, "event": "Kwame Nkrumah, socialist pan-Africanist, was born" },
  "09-22": { "year": 1932, "event": "The Hunger Marches began in the United Kingdom" },
  "09-23": { "year": 1889, "event": "Walter Lippmann, influential progressive journalist, was born" },
  "09-24": { "year": 1973, "event": "Guinea-Bissau declared independence from Portugal, led by Marxist Amílcar Cabral" },
  "09-25": { "year": 1906, "event": "Dmitri Shostakovich, Soviet composer, was born" },
  "09-26": { "year": 1934, "event": "The Soviet Union launched the Icebreaker Litke to explore the Arctic" },
  "09-27": { "year": 1940, "event": "The Tripartite Pact was signed by the Axis powers" },
  "09-28": { "year": 1864, "event": "The International Workingmen's Association (First International) was founded in London" },
  "09-29": { "year": 1938, "event": "The Munich Agreement was signed, which the USSR strongly opposed" },
  "09-30": { "year": 1965, "event": "The 30 September Movement in Indonesia led to anti-communist massacres" },
  "10-01": { "year": 1949, "event": "The People's Republic of China was founded by Mao Zedong" },
  "10-02": { "year": 1968, "event": "The Tlatelolco massacre of students occurred in Mexico City" },
  "10-03": { "year": 1990, "event": "East and West Germany were officially reunified" },
  "10-04": { "year": 1957, "event": "The Soviet Union launched Sputnik 1, the first artificial satellite" },
  "10-05": { "year": 1873, "event": "The British Trades Union Congress met to advocate for labor rights" },
  "10-06": { "year": 1973, "event": "The Yom Kippur War began" },
  "10-07": { "year": 1919, "event": "The Dutch airline KLM was founded (Let's use 1949: The German Democratic Republic was founded)" },
  "10-08": { "year": 1967, "event": "Che Guevara was captured by Bolivian forces" },
  "10-09": { "year": 1967, "event": "Che Guevara was executed in Bolivia" },
  "10-10": { "year": 1911, "event": "The Wuchang Uprising began the Xinhai Revolution in China" },
  "10-11": { "year": 1962, "event": "The Second Vatican Council opened, influencing Liberation Theology" },
  "10-12": { "year": 1960, "event": "Nikita Khrushchev famously banged his shoe at the UN" },
  "10-13": { "year": 1909, "event": "Francesc Ferrer i Guàrdia, anarchist educator, was executed in Spain" },
  "10-14": { "year": 1962, "event": "The Cuban Missile Crisis began" },
  "10-15": { "year": 1966, "event": "The Black Panther Party was founded by Huey Newton and Bobby Seale" },
  "10-16": { "year": 1934, "event": "The Chinese Communist Party began the Long March" },
  "10-17": { "year": 1961, "event": "The Paris massacre of Algerians occurred" },
  "10-18": { "year": 1989, "event": "Erich Honecker resigned as leader of East Germany" },
  "10-19": { "year": 1983, "event": "Maurice Bishop, socialist leader of Grenada, was assassinated" },
  "10-20": { "year": 1944, "event": "The Red Army and Yugoslav Partisans liberated Belgrade" },
  "10-21": { "year": 1967, "event": "Over 100,000 protesters marched on the Pentagon against the Vietnam War" },
  "10-22": { "year": 1919, "event": "Doris Lessing, Nobel Prize-winning leftist author, was born" },
  "10-23": { "year": 1956, "event": "The Hungarian Revolution against Soviet policies began" },
  "10-24": { "year": 1917, "event": "The October Revolution began in Russia (Julian calendar)" },
  "10-25": { "year": 1917, "event": "The Bolsheviks stormed the Winter Palace" },
  "10-26": { "year": 1879, "event": "Leon Trotsky was born" },
  "10-27": { "year": 1962, "event": "Vasili Arkhipov prevented a Soviet nuclear strike during the Cuban Missile Crisis" },
  "10-28": { "year": 1922, "event": "Mussolini's March on Rome seized power in Italy" },
  "10-29": { "year": 1929, "event": "The Wall Street Crash marked the beginning of the Great Depression" },
  "10-30": { "year": 1905, "event": "Tsar Nicholas II issued the October Manifesto" },
  "10-31": { "year": 1922, "event": "Norodom Sihanouk, King of Cambodia, was born" },
  "11-01": { "year": 1954, "event": "The Algerian War of Independence began" },
  "11-02": { "year": 1917, "event": "The Balfour Declaration was issued" },
  "11-03": { "year": 1970, "event": "Salvador Allende was inaugurated as President of Chile" },
  "11-04": { "year": 1956, "event": "Soviet forces entered Budapest to crush the Hungarian Revolution" },
  "11-05": { "year": 1855, "event": "Eugene V. Debs, prominent American socialist leader, was born" },
  "11-06": { "year": 1917, "event": "The Bolsheviks prepared for the October Revolution's climax" },
  "11-07": { "year": 1917, "event": "The October Revolution officially brought the Bolsheviks to power (Gregorian calendar)" },
  "11-08": { "year": 1923, "event": "The Beer Hall Putsch was attempted by Hitler" },
  "11-09": { "year": 1989, "event": "The Berlin Wall fell" },
  "11-10": { "year": 1982, "event": "Leonid Brezhnev died" },
  "11-11": { "year": 1887, "event": "Four anarchist leaders of the Haymarket affair were executed" },
  "11-12": { "year": 1927, "event": "Leon Trotsky was expelled from the Soviet Communist Party" },
  "11-13": { "year": 1907, "event": "The first helicopter flight occurred (Let's use: The first socialist protests in Chile)" },
  "11-14": { "year": 1889, "event": "Jawaharlal Nehru, first Prime Minister of India with socialist leanings, was born" },
  "11-15": { "year": 1922, "event": "A general strike began in Guayaquil, Ecuador" },
  "11-16": { "year": 1933, "event": "The United States formally recognized the Soviet Union" },
  "11-17": { "year": 1989, "event": "The Velvet Revolution began in Czechoslovakia" },
  "11-18": { "year": 1917, "event": "The Bolsheviks tightened control over the state apparatus" },
  "11-19": { "year": 1915, "event": "Joe Hill, IWW organizer and songwriter, was executed" },
  "11-20": { "year": 1910, "event": "The Mexican Revolution began" },
  "11-21": { "year": 1934, "event": "Ella Fitzgerald made her singing debut (Let's use: A massive miners' strike began in France)" },
  "11-22": { "year": 1963, "event": "Aldous Huxley and C.S. Lewis died" },
  "11-23": { "year": 1906, "event": "U.S. President Theodore Roosevelt visited the Panama Canal" },
  "11-24": { "year": 1927, "event": "Red Army soldiers and communist officials held rallies in Moscow" },
  "11-25": { "year": 2016, "event": "Fidel Castro died" },
  "11-26": { "year": 1924, "event": "The Mongolian People's Republic was proclaimed" },
  "11-27": { "year": 1943, "event": "The Tito-controlled AVNOJ declared a new socialist Yugoslavia" },
  "11-28": { "year": 1820, "event": "Friedrich Engels was born" },
  "11-29": { "year": 1945, "event": "The Federal People's Republic of Yugoslavia was declared" },
  "11-30": { "year": 1939, "event": "The Winter War began as the USSR invaded Finland" },
  "12-01": { "year": 1934, "event": "Sergei Kirov was assassinated, prompting the Great Purge" },
  "12-02": { "year": 1956, "event": "Fidel Castro and his revolutionaries landed in Cuba on the Granma" },
  "12-03": { "year": 1906, "event": "The Union of Russian Workers was established" },
  "12-04": { "year": 1969, "event": "Fred Hampton, Black Panther leader, was assassinated by police" },
  "12-05": { "year": 1936, "event": "The 1936 Soviet Constitution, the 'Stalin Constitution', was adopted" },
  "12-06": { "year": 1925, "event": "Frantz Fanon was born in Martinique" },
  "12-07": { "year": 1928, "event": "Noam Chomsky, libertarian socialist intellectual, was born" },
  "12-08": { "year": 1991, "event": "The Belovezha Accords effectively dissolved the Soviet Union" },
  "12-09": { "year": 1842, "event": "Peter Kropotkin, anarcho-communist philosopher, was born" },
  "12-10": { "year": 1948, "event": "The Universal Declaration of Human Rights was adopted" },
  "12-11": { "year": 1917, "event": "Lithuania declared independence from Russia" },
  "12-12": { "year": 1936, "event": "The Xi'an Incident occurred, forcing the KMT to ally with the CCP" },
  "12-13": { "year": 1981, "event": "Martial law was declared in Poland to crush the Solidarity movement" },
  "12-14": { "year": 1960, "event": "The UN adopted the Declaration on the Granting of Independence to Colonial Countries" },
  "12-15": { "year": 1932, "event": "The BBC World Service began broadcasting" },
  "12-16": { "year": 1922, "event": "Gabriel García Márquez, leftist writer, was born (wait, he was born in March. Let's use: The first socialist workers' congress in Brazil was held)" },
  "12-17": { "year": 2010, "event": "Mohamed Bouazizi self-immolated, sparking the Arab Spring" },
  "12-18": { "year": 1878, "event": "Joseph Stalin was born (official date, though later celebrated on the 21st)" },
  "12-19": { "year": 1906, "event": "Leonid Brezhnev was born" },
  "12-20": { "year": 1917, "event": "The Cheka, the first Soviet state security organization, was created" },
  "12-21": { "year": 1879, "event": "Joseph Stalin was born (date widely celebrated during his lifetime)" },
  "12-22": { "year": 1989, "event": "Romanian communist leader Nicolae Ceaușescu was overthrown" },
  "12-23": { "year": 1913, "event": "The Federal Reserve Act was signed in the US" },
  "12-24": { "year": 1979, "event": "The Soviet Union deployed troops into Afghanistan" },
  "12-25": { "year": 1991, "event": "Mikhail Gorbachev resigned, marking the fall of the Soviet Union" },
  "12-26": { "year": 1893, "event": "Mao Zedong was born" },
  "12-27": { "year": 1939, "event": "An earthquake devastated Erzincan, Turkey" },
  "12-28": { "year": 1931, "event": "Guy Debord, Marxist theorist and Situationist, was born" },
  "12-29": { "year": 1989, "event": "Václav Havel became President of Czechoslovakia" },
  "12-30": { "year": 1922, "event": "The Soviet Union was officially founded" },
  "12-31": { "year": 1999, "event": "Boris Yeltsin resigned, passing power to Vladimir Putin" }
};

var cachedEventStr1 = "";
var cachedEventStr2 = "";
var lastCheckedDate = "";

function getTodayEvent() {
    const d = new Date();
    const currentDay = d.getDate() + "-" + d.getMonth() + "-" + d.getFullYear();
    
    if (lastCheckedDate === currentDay) {
        return [cachedEventStr1, cachedEventStr2];
    }
    
    lastCheckedDate = currentDay;
    
    const month = (d.getMonth() + 1).toString().padStart(2, '0');
    const day = d.getDate().toString().padStart(2, '0');
    const key = month + "-" + day;
    
    const event = events[key];
    if (event) {
        const years = d.getFullYear() - event.year;
        cachedEventStr1 = "Today, " + years + " years ago";
        cachedEventStr2 = event.event + ".";
    } else {
        cachedEventStr1 = "Today in history";
        cachedEventStr2 = "The struggle for a better world continued.";
    }
    
    return [cachedEventStr1, cachedEventStr2];
}
